In [ ]:
#importing numpy package in google colab
import numpy as n

In [ ]:
#printing array using numpy keyword as n
array=n.array([1,2,3,4,5])
print("array:",array)

array: [1 2 3 4 5]


In [ ]:
#printing numpy version
print(n.__version__)

1.23.5


In [ ]:
#printing Zero Dimention array
a=n.array(4)
print("0D array:",a)

0D array: 4
1D array: [5 4 3 2 1]


In [ ]:
#printing One Dimention array-1D
a=n.array([5,4,3,2,1])
print("1D array:",a)

1D array: [5 4 3 2 1]


In [ ]:
#used to confirm it's a numpy array or not
type(a)

numpy.ndarray

In [ ]:
#printing Two Dimention array-2D
ar=n.array([[1,2,3],[5,6,7]],dtype=float)
print("2D array:",ar)

2D array: [[1. 2. 3.]
 [5. 6. 7.]]


In [ ]:
#printing the dimention of array
print("Dimention is",ar.ndim)

Dimention is 2


In [ ]:
#printing Three Dimention array-3D
arr=n.array([[[1,2,3],[5,6,7]],[[8,9,10],[1,2,3]]])
print("3D array:",arr)

3D array: [[[ 1  2  3]
  [ 5  6  7]]

 [[ 8  9 10]
  [ 1  2  3]]]


In [ ]:
#print the specific value in array using index subscript[] in-1D
print("Index 1D",a[0])

Index 1D 5


In [ ]:
#print the specific value in array using index subscribt[]in-2D
print("Index 2D",ar[0][2])

Index 2D 3.0


In [ ]:
#print the specific value in array using index subscribt[]in-3D
print("Index 3D",arr[1,0,2])

Index 3D 10


In [ ]:
#perform a slicing operation using ':'slicing operator in 1D
print("slicing 1D",a[0::2])

slicing 1D [5 3 1]


In [ ]:
#perform a slicing operation using ':'slicing operator in 2D
print("slicing 2D",ar[1:3:])

slicing 2D [[5. 6. 7.]]


In [ ]:
#perform a slicing operation using ':'slicing operator in 3d
print("slicing 3D",arr[0:2:1])

slicing 3D [[[ 1  2  3]
  [ 5  6  7]]

 [[ 8  9 10]
  [ 1  2  3]]]


In [ ]:
#perform arithmetic operation(adding two array) 1D+2D
print(a[0]+ar[1][0])

10.0


In [ ]:
#inserting a element into the array
a[3]=3
print("insert",a)

insert [5 4 3 3 1]


In [ ]:
#copy a old array and assign it to the new array
a2=a.copy()
print("copied array is",a2)

copied array is [5 4 3 3 1]


In [ ]:
#perform a concatenation operation (joining two array)
a3=n.concatenate((a,a2))
print("concatenated array is",a3)

concatenated array is [5 4 3 3 1 5 4 3 3 1]


In [ ]:
# Generate a 2x3 array of random numbers between 0 and 1
random_array = n.random.rand(2, 3)
print("Random Array with Shape (2, 3):\n", random_array)

Random Array with Shape (2, 3):
 [[0.99925385 0.39377396 0.04735228]
 [0.89555292 0.38288143 0.15181858]]


In [ ]:
# Generate an array of random numbers from a standard normal distribution
random_array = n.random.randn(3, 3)  # 3x3 array
print("Random Array from Standard Normal Distribution:\n", random_array)

Random Array from Standard Normal Distribution:
 [[-0.04661884 -0.22395034 -1.24246264]
 [ 1.42008877  0.09782582 -1.65824224]
 [-0.77291072  1.50952386  0.33555289]]


In [ ]:
# Create an array
arr = n.array([1, 2, 3, 4, 5])
# Shuffle the array in-place
n.random.shuffle(arr)
arr #new shuffle array

array([1, 3, 4, 2, 5])

In [ ]:
#print an array using random function within a size limit in 1-Dimention
a1= n.random.randint(10,size=4)
print(a)

[5 4 3 3 1]


In [ ]:
#print an array using random function within a size limit in 2-Dimention
a2=n.random.randint(10,size=(2,3))
a2

array([[8, 7, 3],
       [8, 4, 1]])

In [ ]:
#print an array using random function within a size limit in 3-Dimention
a3=n.random.randint(10,size=(3,2,1))
print(a3)

[[[7]
  [4]]

 [[8]
  [4]]

 [[2]
  [4]]]


In [ ]:
#printing the dimention of the array
print(a.ndim)

1


In [ ]:
#printing dimention of array using 'shape'
a.shape

(5,)

In [ ]:
#print the total no.of elements in array using 'size'
a.size

5

In [ ]:
#printing the data type of an array using 'dtype'
print(a.dtype)

int64


In [ ]:
#printing the count of element in array using 'itemsize'
print(a3.itemsize)

8


In [ ]:
#printing the bytes of an array using 'nbytes'
print(a2.nbytes)

48


In [ ]:
#create an array with a range of values
x=n.arange(5)
print(x)

[0 1 2 3 4]


In [ ]:
#create an array with evenly spaced values
y=n.linspace(0,10,5)
y

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#slicing only the first element in array in 3D (row wise)
print(a3[:,0])

[[7]
 [8]
 [2]]


In [ ]:
#slicing only the first array in 3D
print(a3[0,:])

[[7]
 [4]]


In [ ]:
#reshape the array into 4 rows and 1 column
y=n.array([1,9,2,8])
print(y.reshape((4,1)))

[[1]
 [9]
 [2]
 [8]]


In [ ]:
#split the array
z=([1,2,3,4,5])
z1,z2,z3=n.split(z,[2,3])
print(z1,z2,z3)

[1 2] [3] [4 5]


In [ ]:
#create an array using arange function
w=n.arange(16)
print(w)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
#reshape the array into 4 row & 4 columns
print(w.reshape(4,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
#split the array into horizontally
u,l=n.hsplit(w,[2])
print(u)

[0 1]


In [ ]:
print(l)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
#view and change
array=n.array([1,2,3,4,5])

In [ ]:
#view the array using view function
X=array.view()

In [ ]:
#changing the value of the array
X[3]=30

In [ ]:
#print the array
array

array([ 1,  2,  3, 30,  5])

In [ ]:
#copy the existing array
y= array.copy()

In [ ]:
#Base
print(y.base)

None


In [ ]:
#print the base of y
print(y.base)

[1 2 3 4 5]


In [ ]:
#iterating 1D array using for loop
for x in array:
  print(x)

1
2
3
4
5


In [ ]:
#2D array
a=n.array([[10,20,30],[40,50,60]])

In [ ]:
#iterating 2D array
for x in a:
   for y in x:
     print(y)

10
20
30
40
50
60


In [ ]:
b=n.array([[[10,20,30],[40,50,60]],[[1,2,3],[4,5,6]]])

In [ ]:
#iterating 2D array
for x in b:
   for y in x:
      for z in y:
         print(z)

10
20
30
40
50
60
1
2
3
4
5
6


In [ ]:
#sum of array elements
a=n.array([1,2,3,4,5])
a.sum()

15

In [ ]:
#minimum value
a.min()

1

In [ ]:
b=n.array([[10,20,30],[4,5,6]])

In [ ]:
#maximum value in row
b.max(axis=0)

array([10, 20, 30])

In [ ]:
#cummulative sum
b.cumsum(axis=1)

array([[[10, 20, 30],
        [50, 70, 90]],

       [[ 1,  2,  3],
        [ 5,  7,  9]]])

In [ ]:
#mean of array elements
c=n.array([100,200,300])
c.mean()

200.0

In [ ]:
#median of array elements
n.median(c)

200.0

In [ ]:
#compute the correcoefficient
n.corrcoef(b)

array([[1., 1.],
       [1., 1.]])

In [ ]:
#standard deviation
n.std(b)

9.482439911049617

In [ ]:

#printing the variance of an array
variance = n.var(b)
print("Variance:", variance)

Variance: 89.91666666666667


In [ ]:
#sorting
b.sort(axis=0)
b

array([[ 4,  5,  6],
       [10, 20, 30]])

In [ ]:
#element <10 in array
b[b<10]

array([4, 5, 6])

In [ ]:

#element >10 in array
b[b>10]

array([20, 30])

In [ ]:
#flatten
b.ravel()

array([ 4,  5,  6, 10, 20, 30])

In [ ]:
#appending element in beginning
n.append(9,b)

array([ 9,  4,  5,  6, 10, 20, 30])

In [ ]:

#appending element in end
n.append(b,1)

array([ 4,  5,  6, 10, 20, 30,  1])

In [ ]:
#length of array
len(c)

3

In [ ]:
#datatype
b.dtype

dtype('int64')

In [ ]:
#evelnly create values
n.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
#create an identity matrix
n.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#empty array
n.empty((1,2))

array([[1., 1.]])

In [ ]:
#zeros
n.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
#create an array of zeros
n.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
#create an array of ones
n.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
#element wise addition
a1=[1,2,3]
a2=[4,5,6]
n.add(a1,a2)

array([5, 7, 9])

In [ ]:
#element wise subtraction
n.subtract(a1,a2)

array([-3, -3, -3])

In [ ]:
#element wise multiplication
n.multiply(a1,a2)

array([ 4, 10, 18])

In [ ]:
#element wise division
n.divide(a1,a2)

array([0.25, 0.4 , 0.5 ])

In [ ]:
#square root
n.sqrt(2)

1.4142135623730951

In [ ]:
#dot product of two arrays
n.dot(a1,a2)

32

In [ ]:
#check for equal array
a==b

<ipython-input-63-a6f7ccb4d5ba>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a==b


False

In [ ]:
#inserting
n.insert(b,1,2000)

array([   4, 2000,    5,    6,   10,   20,   30])

In [ ]:
#stack arrays
n.hstack((a,c))

array([  1,   2,   3,   4,   5, 100, 200, 300])

In [ ]:
#splitting array
n.vsplit(b,1)

[array([[ 4,  5,  6],
        [10, 20, 30]])]

In [ ]:
#split the array into multiple sub arrays
n.split(b,2)

[array([[10, 20, 30]]), array([[4, 5, 6]])]

In [ ]:
#transpose the array
n.transpose(b)

array([[10,  4],
       [20,  5],
       [30,  6]])

In [ ]:
#delete
n.delete(c,[0])

array([200, 300])

In [ ]:
#row wise element
n.r_[b]

array([[[10, 20, 30],
        [40, 50, 60]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [ ]:
#compute sine of each element in array
n.sin(b)

array([[-0.54402111,  0.91294525, -0.98803162],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [ ]:
#compute sine of each element in array
n.cos(b)

array([[-0.83907153,  0.40808206,  0.15425145],
       [-0.65364362,  0.28366219,  0.96017029]])

In [ ]:
#compute sine of each element in array
n.tan(b)

array([[ 0.64836083,  2.23716094, -6.4053312 ],
       [ 1.15782128, -3.38051501, -0.29100619]])

In [ ]:
#arcsine function
n.arcsin(n.array([0,0.5,1]))

array([0.        , 0.52359878, 1.57079633])

In [ ]:
#arccosine function
n.arccos(n.array([0,0.5,1]))

In [ ]:
#arctan function
n.arctan(n.array([0,0.5,1]))

array([0.        , 0.46364761, 0.78539816])

In [ ]:
#computing inverse trignometric functions
val=n.array([-1,-0.5,-1])

In [ ]:
#inverse arcsine function
n.arcsin(val)

array([-1.57079633, -0.52359878, -1.57079633])

In [ ]:
#inverse arccosine function
n.arccos(val)

array([3.14159265, 2.0943951 , 3.14159265])

In [ ]:
#inverse arctane function
n.arctan(val)

array([-0.78539816, -0.46364761, -0.78539816])

In [ ]:
# Compute the 10th, 50th, and 90th percentiles
percentiles = n.percentile(arr, [10, 50, 90])

print("Percentiles:", percentiles)

Percentiles: [1.4 3.  4.6]


In [ ]:
# Create two arrays
arr1 = n.array([True, False, True])
arr2 = n.array([False, True, True])

In [ ]:

# Element-wise AND
result_and = arr1 & arr2
print("Element-wise AND:", result_and)

Element-wise AND: [False False  True]


In [ ]:
# Element-wise OR
result_or = arr1 | arr2
print("Element-wise OR:", result_or)

Element-wise OR: [ True  True  True]


In [ ]:
# Element-wise NOT
result_not = ~arr1
print("Element-wise NOT:", result_not)

Element-wise NOT: [False  True False]


In [ ]:
A = n.array([[1, 2], [3, 4]])
B = n.array([[5, 6], [7, 8]])

In [ ]:
#printing inverse of the matrix
A_inverse = n.linalg.inv(A)
print("Matrix Inverse:")
print(A_inverse)

Matrix Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#eigen values& vectors of the matrix
eigenvalues, eigenvectors = n.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
#determinant of the matrix
det_A = n.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: -2.0000000000000004


In [ ]:
# Create an array
arr = n.array([1, 2, 3, 4, 5])
# Save the array to a binary file
n.save('saved_array.npy', arr)

In [ ]:
# Load the array from the binary file
loaded_arr = n.load('saved_array.npy')

print("Original Array:", arr)
print("Loaded Array:", loaded_arr)

Original Array: [1 2 3 4 5]
Loaded Array: [1 2 3 4 5]
